// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
//
// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  projectId: "studio-3849301474-e0c08",
  appId: "1:492243028741:web:f3206d8bceefbb72d6456c",
  storageBucket: "studio-3849301474-e0c08.appspot.com",
  apiKey: "AIzaSyBPw1vDEJM0HHqypRqa7MS2L6dscEsH9Aw",
  authDomain: "studio-3849301474-e0c08.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "492243028741",
};
